package com.jaaliska.activitycalendar.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val CrimsonLightColors = lightColorScheme(
    primary = Color(0xFF9E3D54),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD9DE),
    onPrimaryContainer = Color(0xFF410015),
    secondary = Color(0xFF76565B),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFEDADE),
    onSecondaryContainer = Color(0xFF2E1319),
    tertiary = Color(0xFF815159),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFEDADE),
    onTertiaryContainer = Color(0xFF360D17),
    error = Color(0xFFB3261E),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFF9DEDC),
    onErrorContainer = Color(0xFF410E0B),
    background = Color(0xFFFEF8F9),
    onBackground = Color(0xFF211A1B),
    surface = Color(0xFFFEF8F9),
    onSurface = Color(0xFF211A1B),
    surfaceVariant = Color(0xFFF3DDE0),
    onSurfaceVariant = Color(0xFF544245),
    surfaceTint = Color(0xFF9E3D54),
    inverseSurface = Color(0xFF372E2F),
    inverseOnSurface = Color(0xFFF9EEEF),
    inversePrimary = Color(0xFFFFB2BE),
    outline = Color(0xFF857275),
    outlineVariant = Color(0xFFD7C1C4),
    scrim = Color(0xFF000000),
    surfaceDim = Color(0xFFE2D7D9),
    surfaceBright = Color(0xFFFEF8F9),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFCF1F2),
    surfaceContainer = Color(0xFFF6EBED),
    surfaceContainerHigh = Color(0xFFF1E6E7),
    surfaceContainerHighest = Color(0xFFEBE0E1),
)

val CrimsonDarkColors = darkColorScheme(
    primary = Color(0xFFFFB2BE),
    onPrimary = Color(0xFF660127),
    primaryContainer = Color(0xFF82233D),
    onPrimaryContainer = Color(0xFFFFD9DE),
    secondary = Color(0xFFE3BDC2),
    onSecondary = Color(0xFF45282D),
    secondaryContainer = Color(0xFF5D3F43),
    onSecondaryContainer = Color(0xFFFEDADE),
    tertiary = Color(0xFFF0B8C0),
    onTertiary = Color(0xFF4E232C),
    tertiaryContainer = Color(0xFF673942),
    onTertiaryContainer = Color(0xFFFEDADE),
    error = Color(0xFFF2B8B5),
    onError = Color(0xFF601410),
    errorContainer = Color(0xFF8C1D18),
    onErrorContainer = Color(0xFFF9DEDC),
    background = Color(0xFF191112),
    onBackground = Color(0xFFEBE0E1),
    surface = Color(0xFF191112),
    onSurface = Color(0xFFEBE0E1),
    surfaceVariant = Color(0xFF544245),
    onSurfaceVariant = Color(0xFFD7C1C4),
    surfaceTint = Color(0xFFFFB2BE),
    inverseSurface = Color(0xFFEBE0E1),
    inverseOnSurface = Color(0xFF372E2F),
    inversePrimary = Color(0xFF9E3D54),
    outline = Color(0xFFA08C8E),
    outlineVariant = Color(0xFF544245),
    scrim = Color(0xFF000000),
    surfaceDim = Color(0xFF191112),
    surfaceBright = Color(0xFF403738),
    surfaceContainerLowest = Color(0xFF160B0D),
    surfaceContainerLow = Color(0xFF211A1B),
    surfaceContainer = Color(0xFF251E1F),
    surfaceContainerHigh = Color(0xFF302829),
    surfaceContainerHighest = Color(0xFF3B3334),
)

