package com.jaaliska.activitycalendar.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val OrangeLightColors = lightColorScheme(
    primary = Color(0xFF885030),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFEDCCA),
    onPrimaryContainer = Color(0xFF2F1500),
    secondary = Color(0xFF6F5A4F),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF7DDD0),
    onSecondaryContainer = Color(0xFF28180D),
    tertiary = Color(0xFF765847),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDBC9),
    onTertiaryContainer = Color(0xFF2D1602),
    error = Color(0xFFB3261E),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFF9DEDC),
    onErrorContainer = Color(0xFF410E0B),
    background = Color(0xFFFFF8F5),
    onBackground = Color(0xFF201A17),
    surface = Color(0xFFFFF8F5),
    onSurface = Color(0xFF201A17),
    surfaceVariant = Color(0xFFF1DFD6),
    onSurfaceVariant = Color(0xFF52443D),
    surfaceTint = Color(0xFF885030),
    inverseSurface = Color(0xFF362F2C),
    inverseOnSurface = Color(0xFFF8EFEA),
    inversePrimary = Color(0xFFFBB792),
    outline = Color(0xFF83746C),
    outlineVariant = Color(0xFFD4C3BA),
    scrim = Color(0xFF000000),
    surfaceDim = Color(0xFFE1D8D4),
    surfaceBright = Color(0xFFFFF8F5),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFBF2ED),
    surfaceContainer = Color(0xFFF5ECE8),
    surfaceContainerHigh = Color(0xFFEFE6E2),
    surfaceContainerHighest = Color(0xFFEAE1DC),
)

val OrangeDarkColors = darkColorScheme(
    primary = Color(0xFFFBB792),
    onPrimary = Color(0xFF522302),
    primaryContainer = Color(0xFF6D391A),
    onPrimaryContainer = Color(0xFFFEDCCA),
    secondary = Color(0xFFDAC2B5),
    onSecondary = Color(0xFF3E2C23),
    secondaryContainer = Color(0xFF564338),
    onSecondaryContainer = Color(0xFFF7DDD0),
    tertiary = Color(0xFFE3BFAC),
    onTertiary = Color(0xFF442A1C),
    tertiaryContainer = Color(0xFF5D4031),
    onTertiaryContainer = Color(0xFFFFDBC9),
    error = Color(0xFFF2B8B5),
    onError = Color(0xFF601410),
    errorContainer = Color(0xFF8C1D18),
    onErrorContainer = Color(0xFFF9DEDC),
    background = Color(0xFF19120E),
    onBackground = Color(0xFFEAE1DC),
    surface = Color(0xFF19120E),
    onSurface = Color(0xFFEAE1DC),
    surfaceVariant = Color(0xFF52443D),
    onSurfaceVariant = Color(0xFFD4C3BA),
    surfaceTint = Color(0xFFFBB792),
    inverseSurface = Color(0xFFEAE1DC),
    inverseOnSurface = Color(0xFF362F2C),
    inversePrimary = Color(0xFF885030),
    outline = Color(0xFF9E8D85),
    outlineVariant = Color(0xFF52443D),
    scrim = Color(0xFF000000),
    surfaceDim = Color(0xFF19120E),
    surfaceBright = Color(0xFF3F3834),
    surfaceContainerLowest = Color(0xFF150C07),
    surfaceContainerLow = Color(0xFF201A17),
    surfaceContainer = Color(0xFF241E1B),
    surfaceContainerHigh = Color(0xFF2F2925),
    surfaceContainerHighest = Color(0xFF3A3330),
)

